export const en = {
  "Cancel": "Cancel",
  "Save": "Save",
  "Review": "Review",
  "Enter text": "Enter text",
  "Email": "Email",
  "Enter email": "Enter email",
  "Enter password": "Enter password",
  "Enter your name": "Enter your name",
  "GooseTrack's Calendar view provides a comprehensive overview of your schedule, displaying all your tasks, events, and appointments in a visually appealing and intuitive layout.": "GooseTrack's Calendar view provides a comprehensive overview of your schedule, displaying all your tasks, events, and appointments in a visually appealing and intuitive layout.",
  "Log In": "Log In",
  "Name": "Name",
  "Password": "Password",
  "Sign Up": "Sign Up",
  "This is a CORRECT email": "This is a CORRECT email",
  "This is a CORRECT password": "This is a CORRECT password",
  "Well done": "Well done",
  "email is a required field": "email is a required field",
  "email must be a valid email": "email must be a valid email",
  "name is a required field": "name is a required field",
  "password is a required field": "password is a required field",
  "password must be at least 4 characters": "password must be at least 4 characters",
}
