export const funUk = {
  "Add task": "Придумай справу",
  "Add": "Додай",
  "After performing heavy algorithms, we came to the conclusion that your intended number is:": "Після всіх ахалай-махалай, я дійшов висновку. Ти дурачо... ой, тобто твоє число:",
  "All in": "Все і одразу",
  "Amazing": "Най тя качка компне",
  "Analising your minds": "Лізу тобі у голову",
  "Are you really want to delete this review?": "Ти що відмовляєшся від свого прокльону? Це вже 100%?",
  "Are you really want to delete this task?": "Не відкладай справи на завтра. Те що ти видалиш її нічого не змінить. Ти дійсно цього хочеш?",
  "Birthday": "Світоявлення",
  "Calendar": "Всезнайка",
  "Cancel": "Ні-ні-ні",
  "Comment is a required field": "Твоя думка обов'язкова",
  "Comment must be at least 3 characters": "Не жалій. Мінімум 3 символи",
  "Day": "Деньочки",
  "Data was updated successfully": "Сервер зберіг те що ти написав",
  "Default": "Як гусь каже",
  "Delete Review": "Видалити прокльон",
  "Delete Task": "Видалити справу",
  "Don't show it again?": "То може не показувати це знову?",
  "Done": "Дошка шани",
  "Edit": "Переписати",
  "Email is a required field": "Гусь-mail - обов'язковий",
  "Email must be a valid email": "Гусь-mail повинен бути дійсним",
  "Email": "Гусь-mail",
  "End date can't before start date": "Ти що, я таке не порахую",
  "End date is a required field": "Заповни кінцеву дату",
  "End date": "Кінцева дата",
  "End time should be later than start time": "Повір, ти не встигнеш виконати це завдання. Час закінчення завдання має бути пізніше ніж час початку.",
  "End": "Закінчуєсі",
  "Enter email": "Впишіть той гусь-mail",
  "Enter password": "Впишіть якісь зірочки",
  "Enter text": "Вводь свій прокльончик",
  "Enter time": "Коли то буде?",
  "Enter title": "Як то сі називає?",
  "Enter your birthday": "Впиши свій день світоявлення",
  "Enter your email": "Впишіть той гусь-mail",
  "Enter your name": "Впиши своє назвисько",
  "Enter your number": "Введи цифру",
  "Enter your phone": "А де тобі дзвонити?",
  "Enter your skype": "Може ше Skype?",
  "Enter your user name": "Впиши своє назвисько",
  "Feedback": "Прокльони",
  "Fething analitics library": "Стягування всяких штук",
  "Find number algorithm": "А я знаю, що ти знаєш",
  "Generating possible solutions": "Зара буде",
  "Go Back": "Повирнути що було",
  "GooseTrack is an all-in-one productivity tool that helps you stay on top of your tasks, events, and deadlines. Say goodbye to scattered to-do lists and hello to streamlined productivity with GooseTrack.": "GooseTrack - це все в одному інструменті продуктивності, який допомагає вам керувати вашими завданнями, подіями та строками. Попрощайтеся з розкиданими списками справ і привітайте з організованою продуктивністю з GooseTrack.",
  "GooseTrack offers easy access to your account settings, calendar, and filters. The My Account section allows you to manage your profile information and preferences, while the calendar provides a quick and convenient way to view your upcoming events and tasks.": "GooseTrack надає легкий доступ до налаштувань облікового запису, календаря та фільтрів. Розділ Мій обліковий запис дозволяє вам керувати інформацією про профіль та вподобаннями, а календар надає швидкий та зручний спосіб перегляду майбутніх подій та завдань.",
  "GooseTrack's Calendar view provides a comprehensive overview of your schedule, displaying all your tasks, events, and appointments in a visually appealing and intuitive layout.": "Календарний перегляд GooseTrack надає всебічний огляд вашого графіка, відображаючи всі ваші завдання, події та призначення в привабливому та інтуїтивно зрозумілому макеті.",
  "High": "На вчора",
  "I don't know the value": "Я точно не знаю значення",
  "In progress": "Робиться",
  "Let's go of the past and focus on the present!": "Будь як гусь! Плануй тут і зараз",
  "Let's go": "Будь як гусь!",
  "Loading": "Потерпи",
  "Log In": "Повернутись до зграї",
  "Log in": "Повернутись до зграї",
  "Log out": "Покинути це",
  "Low": "Мізерний",
  "Magic": "Меджик",
  "Medium": "Почті уржент",
  "Month": "Місяченьки",
  "My Account": "Мій справочник",
  "Name can have maximum 40 characters": "Назвисько може містити максимум 40 символів",
  "Name is a required field": "Назвисько - обов'язкове",
  "Name": "Назвисько",
  "No": "Ні",
  "Number is a required field": "Без числа я не вгадаю твоє число",
  "Oh! The page you were looking for was probably stolen by geese": "Ой! Сторінку, яку ви шукали, ймовірно вкрали гуси",
  "One": "",
  "Password is a required field": "Зірочки - обов'язкові",
  "Password must be at least 6 characters": "Зірочки повинні містити щонайменше 6 символів",
  "Password": "Якісь зірочки",
  "Phone can have maximum 20 characters": "Забагато символів. Я не додзвонюсь.",
  "Phone": "Мобілка",
  "Priority is a required field": "Важливість - це важливе поле.",
  "Productivity": "Дужість",
  "Rating is a required field": "То добре чи зле? Оціни!",
  "Rating": "Оціночки",
  "Retina recognition": "Сканування твого ока",
  "Review": "Прокльон",
  "Reviews": "Чиїсь прокльони",
  "Save changes": "Збережемося?",
  "Save": "Запам'ятати",
  "Sidebar": "Бічне меню",
  "Sign Up": "Стати гусем",
  "Sign up": "Стати гусем",
  "Skype": "Skype",
  "Start date is a required field": "Заповни початкову дату",
  "Start date": "Стартова дата",
  "Start": "Починаєсі",
  "The user was verified": "Гусь підтвердив твою особу",
  "This is a CORRECT birthday": "Це ПРАВИЛЬНИЙ день світоявлення",
  "This is a CORRECT email": "Це ПРАВИЛЬНИЙ гусь-mail",
  "This is a CORRECT end date": "Це ПРАВИЛЬНА кінцева дата",
  "This is a CORRECT name": "Це ПРАВИЛЬНЕ назвисько",
  "This is a CORRECT password": "Це ПРАВИЛЬНІ зірочки",
  "This is a CORRECT skype": "Це ПРАВИЛЬНИЙ Skype",
  "This is a CORRECT start date": "Це ПРАВИЛЬНА стартова дата",
  "This is a CORRECT time": "Це ПРАВИЛЬНИЙ час",
  "This is a CORRECT title": "Це ПРАВИЛЬНА назва",
  "This value is CORRECT for the algorithm": "Це значення є коректне для ахалай-махалай",
  "Title is a required field": "Назва - обов'язкове поле",
  "Title": "Назва",
  "To do": "Що я хочу?",
  "User Name": "Назвисько юзера",
  "User Panel": "Панель користувача",
  "User Profile": "Мій справочник",
  "User was updated successfully": "Наче ОК. Ти збережений)",
  "User": "Юзер",
  "View": "",
  "We send a verify letter to your email!": "Ми відправили гуся для перевірки на вашу електронну пошту!",
  "Well done": "Красавчик",
  "Yes": "Так",
  "of the past and focus on the present!": "Плануй тут і зараз",

  // Week days
  "Mon": "Пн",
  "Tue": "Вт",
  "Wed": "Ср",
  "Thu": "Чт",
  "Fri": "Пт",
  "Sat": "Сб",
  "Sun": "Нд",
}
