export const uk = {
  "Add task": "Добавити завдання",
  "Add": "Добавити",
  "After performing heavy algorithms, we came to the conclusion that your intended number is:": "Після проведення важких алгоритмів та аналізу ми дійшли висновку, що твоє задумане вами число:",
  "All in": "Все в",
  "Amazing": "Дивовижно",
  "Analising your minds": "Аналіз ваших думок",
  "Are you really want to delete this review?": "Ви дійсно хочете видалити цей відгук",
  "Are you really want to delete this task?": "Ви дійсно хочете видалити це завдання?",
  "Birthday": "День народження",
  "Calendar": "Календар",
  "Cancel": "Відмінити",
  "Comment is a required field": "Коментар є обов'язковим",
  "Comment must be at least 3 characters": "Коментар має містити як мінімум 3 символа",
  "Day": "День",
  "Default": "За замовчуванням",
  "Delete Review": "Вадилити відгук",
  "Delete Task": "Видалити завдання",
  "Don't show it again?": "Чи показувати наступний раз?",
  "Done": "Готово",
  "Edit": "Редагувати",
  "Email is a required field": "Email є обов'язковим полем",
  "Email must be a valid email": "Email має бути правильним",
  "Email": "Email",
  "End date can't before start date": "Кінцева дата не має бути менша ніж початкова",
  "End date is a required field": "Кінцева дата має бути заповнена",
  "End date": "Кінцева дата",
  "End time should be later than start time": "Час закінчення має бути раніше ніж час початку",
  "End": "Закінчується",
  "Enter email": "Введіть email",
  "Enter password": "Введіть пароль",
  "Enter text": "Введіть текст",
  "Enter time": "Введіть час",
  "Enter title": "Введіть назву",
  "Enter your birthday": "Введіть ваш день народження",
  "Enter your email": "Введіть ваш email",
  "Enter your name": "Введіть ваше ім'я",
  "Enter your number": "Введіть ваше число",
  "Enter your phone": "Введіть ваш телефон",
  "Enter your skype": "Введіть ваш Skype",
  "Enter your user name": "Введіть ваш нікнейм",
  "Feedback": "Відгуки",
  "Fething analitics library": "Стягування бібліотеки аналізу",
  "Find number algorithm": "Алгоритм знаходження числа",
  "For the correct value try to use dates which has more then 10 tasks between each other.": "Для коректного розрахунку намагайтеся вибрати дати між якими є більше ніж 10 завдань.",
  "Generating possible solutions": "Генерування можливих рішень",
  "Go Back": "Повернутись назад",
  "GooseTrack is an all-in-one productivity tool that helps you stay on top of your tasks, events, and deadlines. Say goodbye to scattered to-do lists and hello to streamlined productivity with GooseTrack.": "GooseTrack - це все в одному інструменті продуктивності, який допомагає вам керувати вашими завданнями, подіями та строками. Попрощайтеся з розкиданими списками справ і привітайте з організованою продуктивністю з GooseTrack.",
  "GooseTrack offers easy access to your account settings, calendar, and filters. The My Account section allows you to manage your profile information and preferences, while the calendar provides a quick and convenient way to view your upcoming events and tasks.": "GooseTrack надає легкий доступ до налаштувань облікового запису, календаря та фільтрів. Розділ Мій обліковий запис дозволяє вам керувати інформацією про профіль та вподобаннями, а календар надає швидкий та зручний спосіб перегляду майбутніх подій та завдань.",
  "GooseTrack's Calendar view provides a comprehensive overview of your schedule, displaying all your tasks, events, and appointments in a visually appealing and intuitive layout.": "Календарний перегляд GooseTrack надає всебічний огляд вашого графіка, відображаючи всі ваші завдання, події та призначення в привабливому та інтуїтивно зрозумілому макеті.",
  "High": "Високий",
  "I don't know the value": "Я не знатиму цього значення",
  "In progress": "В процесі",
  "Let's go of the past and focus on the present!": "Зроби це! Плануй тут і зараз",
  "Let's go": "Зроби це",
  "Loading": "Завантаження",
  "Log In": "Увійти",
  "Log in": "Увійти",
  "Log out": "Вийти",
  "Low": "Низький",
  "Magic": "Магія",
  "Medium": "Середній",
  "Month": "Місяці",
  "My Account": "Мій акаунт",
  "Name can have maximum 40 characters": "Ім'я має містити максимум 40 символів",
  "Name is a required field": "Ім'я є обов'язковим полем",
  "Name": "Ім'я",
  "No": "Ні",
  "Number is a required field": "Число це обов'язкове поле",
  "Oh! The page you were looking for was probably stolen by geese": "Ой! Сторінку, яку ви шукаєте не існує",
  "One": "",
  "Password is a required field": "Пароль обов'язковий",
  "Password must be at least 6 characters": "Пароль має містити щонайменше 6 символів",
  "Password": "Пароль",
  "Phone can have maximum 20 characters": "Телефон має містити максимум 20 символів",
  "Phone": "Телефон",
  "Priority is a required field": "Важливість це обов'язкове поле",
  "Productivity": "Продуктивність",
  "Rating is a required field": "Рейтинг є обов'яковим помлем",
  "Rating": "Рейтинг",
  "Retina recognition": "Сканування сітківки ока",
  "Review": "Відгук",
  "Reviews": "Відгуки",
  "Save changes": "Зберегти зміни",
  "Save": "Запам'ятати",
  "Select Dates": "Виберіть Дати",
  "Sidebar": "Бічне меню",
  "Sign Up": "Зарегіструватись",
  "Sign up": "Зарегіструватись",
  "Skype": "Skype",
  "Start date is a required field": "Початкова дата має бути заповнена",
  "Start date": "Стартова дата",
  "Start": "Початок",
  "The data will be used for the formula of the productivity coefficient.": "Дані поля будуть застосовані для розрахунку коефіцієнту продуктивності.",
  "The user was verified": "Користувач був верифікований",
  "This is a CORRECT birthday": "Це ПРАВИЛЬНИЙ день народження",
  "This is a CORRECT email": "Це ПРАВИЛЬНИЙ email",
  "This is a CORRECT end date": "Це ПРАВИЛЬНА кінцева дата",
  "This is a CORRECT name": "Це ПРАВИЛЬНЕ ім'я",
  "This is a CORRECT password": "Це ПРАВИЛЬНИЙ пароль",
  "This is a CORRECT skype": "Це ПРАВИЛЬНИЙ Skype",
  "This is a CORRECT start date": "Це ПРАВИЛЬНА стартова дата",
  "This is a CORRECT time": "Це ПРАВИЛЬНИЙ час",
  "This is a CORRECT title": "Це ПРАВИЛЬНА назва",
  "This value is CORRECT for the algorithm": "Це значення КОРЕКТНЕ для розрахунків",
  "Title is a required field": "Назва - обов'язкове поле",
  "Title": "Назва",
  "To do": "Зробити",
  "User Name": "Ім'я користувача",
  "User Panel": "Панель користувача",
  "User Profile": "Мій профіль",
  "User was updated successfully": "Користувач був успішно оновлений",
  "User": "Користувач",
  "View": "",
  "We send a verify letter to your email!": "Ми відправили лист на вашу електронну пошту!",
  "Well done": "Так тримати",
  "Yes": "Так",
  "of the past and focus on the present!": "Плануй тут і зараз",

  // Week days
  "Mon": "Пн",
  "Tue": "Вт",
  "Wed": "Ср",
  "Thu": "Чт",
  "Fri": "Пт",
  "Sat": "Сб",
  "Sun": "Нд",
}
