export const queryKeys = Object.freeze({
  login: 'login',
  register: 'register',
  logout: 'logout',
  getReviews: 'getReviews',
  addReview: 'addReview',
  updateReview: 'updateReview',
  deleteReview: 'deleteReview',
  getUsers: 'getUsers',
  updateUser: 'updateUser',
  getTasks: 'getTasks',
  createTask: 'createTask',
  updateTask: 'updateTask',
  deleteTask: 'deleteTask',
})
